#pragma once

#define BLACKDESK_CPPLIB_TOSTRING(x) BLACKDESK_CPPLIB_TOSTRING_IMPL(x)
#define BLACKDESK_CPPLIB_TOSTRING_IMPL(x) #x

#define BLACKDESK_CPPLIB_UNUSED(x) (void)(x)

// Thanks https://disenone.github.io/2021/03/31/cpp-preprocess

#define BLACKDESK_CPPLIB_LPAREN() (

#define BLACKDESK_CPPLIB_RPAREN() )

#define BLACKDESK_CPPLIB_COMMA() ,

#define BLACKDESK_CPPLIB_SEMICOLON() ;

#define BLACKDESK_CPPLIB_EMPTY()

#define BLACKDESK_CPPLIB_HASHHASH # ## #

#define BLACKDESK_CPPLIB_IDENTITY(arg0) arg0

#define BLACKDESK_CPPLIB_CONCAT(arg0, arg1) \
        BLACKDESK_CPPLIB_CONCAT_IMPL(arg0, arg1)
#define BLACKDESK_CPPLIB_CONCAT_IMPL(arg0, arg1) arg0##arg1

#define BLACKDESK_CPPLIB_BOOL(arg0) \
        BLACKDESK_CPPLIB_CONCAT(BLACKDESK_CPPLIB_BOOL_, arg0)
#define BLACKDESK_CPPLIB_BOOL_0 0
#define BLACKDESK_CPPLIB_BOOL_1 1
#define BLACKDESK_CPPLIB_BOOL_2 1
#define BLACKDESK_CPPLIB_BOOL_3 1
#define BLACKDESK_CPPLIB_BOOL_4 1
#define BLACKDESK_CPPLIB_BOOL_5 1
#define BLACKDESK_CPPLIB_BOOL_6 1
#define BLACKDESK_CPPLIB_BOOL_7 1
#define BLACKDESK_CPPLIB_BOOL_8 1
#define BLACKDESK_CPPLIB_BOOL_9 1
#define BLACKDESK_CPPLIB_BOOL_10 1
#define BLACKDESK_CPPLIB_BOOL_11 1
#define BLACKDESK_CPPLIB_BOOL_12 1
#define BLACKDESK_CPPLIB_BOOL_13 1
#define BLACKDESK_CPPLIB_BOOL_14 1
#define BLACKDESK_CPPLIB_BOOL_15 1
#define BLACKDESK_CPPLIB_BOOL_16 1
#define BLACKDESK_CPPLIB_BOOL_17 1
#define BLACKDESK_CPPLIB_BOOL_18 1
#define BLACKDESK_CPPLIB_BOOL_19 1
#define BLACKDESK_CPPLIB_BOOL_20 1
#define BLACKDESK_CPPLIB_BOOL_21 1
#define BLACKDESK_CPPLIB_BOOL_22 1
#define BLACKDESK_CPPLIB_BOOL_23 1
#define BLACKDESK_CPPLIB_BOOL_24 1
#define BLACKDESK_CPPLIB_BOOL_25 1
#define BLACKDESK_CPPLIB_BOOL_26 1
#define BLACKDESK_CPPLIB_BOOL_27 1
#define BLACKDESK_CPPLIB_BOOL_28 1
#define BLACKDESK_CPPLIB_BOOL_29 1
#define BLACKDESK_CPPLIB_BOOL_30 1
#define BLACKDESK_CPPLIB_BOOL_31 1
#define BLACKDESK_CPPLIB_BOOL_32 1
#define BLACKDESK_CPPLIB_BOOL_33 1
#define BLACKDESK_CPPLIB_BOOL_34 1
#define BLACKDESK_CPPLIB_BOOL_35 1
#define BLACKDESK_CPPLIB_BOOL_36 1
#define BLACKDESK_CPPLIB_BOOL_37 1
#define BLACKDESK_CPPLIB_BOOL_38 1
#define BLACKDESK_CPPLIB_BOOL_39 1
#define BLACKDESK_CPPLIB_BOOL_40 1
#define BLACKDESK_CPPLIB_BOOL_41 1
#define BLACKDESK_CPPLIB_BOOL_42 1
#define BLACKDESK_CPPLIB_BOOL_43 1
#define BLACKDESK_CPPLIB_BOOL_44 1
#define BLACKDESK_CPPLIB_BOOL_45 1
#define BLACKDESK_CPPLIB_BOOL_46 1
#define BLACKDESK_CPPLIB_BOOL_47 1
#define BLACKDESK_CPPLIB_BOOL_48 1
#define BLACKDESK_CPPLIB_BOOL_49 1
#define BLACKDESK_CPPLIB_BOOL_50 1
#define BLACKDESK_CPPLIB_BOOL_51 1
#define BLACKDESK_CPPLIB_BOOL_52 1
#define BLACKDESK_CPPLIB_BOOL_53 1
#define BLACKDESK_CPPLIB_BOOL_54 1
#define BLACKDESK_CPPLIB_BOOL_55 1
#define BLACKDESK_CPPLIB_BOOL_56 1
#define BLACKDESK_CPPLIB_BOOL_57 1
#define BLACKDESK_CPPLIB_BOOL_58 1
#define BLACKDESK_CPPLIB_BOOL_59 1
#define BLACKDESK_CPPLIB_BOOL_60 1
#define BLACKDESK_CPPLIB_BOOL_61 1
#define BLACKDESK_CPPLIB_BOOL_62 1
#define BLACKDESK_CPPLIB_BOOL_63 1
#define BLACKDESK_CPPLIB_BOOL_64 1
#define BLACKDESK_CPPLIB_BOOL_65 1
#define BLACKDESK_CPPLIB_BOOL_66 1
#define BLACKDESK_CPPLIB_BOOL_67 1
#define BLACKDESK_CPPLIB_BOOL_68 1
#define BLACKDESK_CPPLIB_BOOL_69 1
#define BLACKDESK_CPPLIB_BOOL_70 1
#define BLACKDESK_CPPLIB_BOOL_71 1
#define BLACKDESK_CPPLIB_BOOL_72 1
#define BLACKDESK_CPPLIB_BOOL_73 1
#define BLACKDESK_CPPLIB_BOOL_74 1
#define BLACKDESK_CPPLIB_BOOL_75 1
#define BLACKDESK_CPPLIB_BOOL_76 1
#define BLACKDESK_CPPLIB_BOOL_77 1
#define BLACKDESK_CPPLIB_BOOL_78 1
#define BLACKDESK_CPPLIB_BOOL_79 1
#define BLACKDESK_CPPLIB_BOOL_80 1
#define BLACKDESK_CPPLIB_BOOL_81 1
#define BLACKDESK_CPPLIB_BOOL_82 1
#define BLACKDESK_CPPLIB_BOOL_83 1
#define BLACKDESK_CPPLIB_BOOL_84 1
#define BLACKDESK_CPPLIB_BOOL_85 1
#define BLACKDESK_CPPLIB_BOOL_86 1
#define BLACKDESK_CPPLIB_BOOL_87 1
#define BLACKDESK_CPPLIB_BOOL_88 1
#define BLACKDESK_CPPLIB_BOOL_89 1
#define BLACKDESK_CPPLIB_BOOL_90 1
#define BLACKDESK_CPPLIB_BOOL_91 1
#define BLACKDESK_CPPLIB_BOOL_92 1
#define BLACKDESK_CPPLIB_BOOL_93 1
#define BLACKDESK_CPPLIB_BOOL_94 1
#define BLACKDESK_CPPLIB_BOOL_95 1
#define BLACKDESK_CPPLIB_BOOL_96 1
#define BLACKDESK_CPPLIB_BOOL_97 1
#define BLACKDESK_CPPLIB_BOOL_98 1
#define BLACKDESK_CPPLIB_BOOL_99 1
#define BLACKDESK_CPPLIB_BOOL_100 1
#define BLACKDESK_CPPLIB_BOOL_101 1
#define BLACKDESK_CPPLIB_BOOL_102 1
#define BLACKDESK_CPPLIB_BOOL_103 1
#define BLACKDESK_CPPLIB_BOOL_104 1
#define BLACKDESK_CPPLIB_BOOL_105 1
#define BLACKDESK_CPPLIB_BOOL_106 1
#define BLACKDESK_CPPLIB_BOOL_107 1
#define BLACKDESK_CPPLIB_BOOL_108 1
#define BLACKDESK_CPPLIB_BOOL_109 1
#define BLACKDESK_CPPLIB_BOOL_110 1
#define BLACKDESK_CPPLIB_BOOL_111 1
#define BLACKDESK_CPPLIB_BOOL_112 1
#define BLACKDESK_CPPLIB_BOOL_113 1
#define BLACKDESK_CPPLIB_BOOL_114 1
#define BLACKDESK_CPPLIB_BOOL_115 1
#define BLACKDESK_CPPLIB_BOOL_116 1
#define BLACKDESK_CPPLIB_BOOL_117 1
#define BLACKDESK_CPPLIB_BOOL_118 1
#define BLACKDESK_CPPLIB_BOOL_119 1
#define BLACKDESK_CPPLIB_BOOL_120 1
#define BLACKDESK_CPPLIB_BOOL_121 1
#define BLACKDESK_CPPLIB_BOOL_122 1
#define BLACKDESK_CPPLIB_BOOL_123 1
#define BLACKDESK_CPPLIB_BOOL_124 1
#define BLACKDESK_CPPLIB_BOOL_125 1
#define BLACKDESK_CPPLIB_BOOL_126 1
#define BLACKDESK_CPPLIB_BOOL_127 1
#define BLACKDESK_CPPLIB_BOOL_128 1
#define BLACKDESK_CPPLIB_BOOL_129 1
#define BLACKDESK_CPPLIB_BOOL_130 1
#define BLACKDESK_CPPLIB_BOOL_131 1
#define BLACKDESK_CPPLIB_BOOL_132 1
#define BLACKDESK_CPPLIB_BOOL_133 1
#define BLACKDESK_CPPLIB_BOOL_134 1
#define BLACKDESK_CPPLIB_BOOL_135 1
#define BLACKDESK_CPPLIB_BOOL_136 1
#define BLACKDESK_CPPLIB_BOOL_137 1
#define BLACKDESK_CPPLIB_BOOL_138 1
#define BLACKDESK_CPPLIB_BOOL_139 1
#define BLACKDESK_CPPLIB_BOOL_140 1
#define BLACKDESK_CPPLIB_BOOL_141 1
#define BLACKDESK_CPPLIB_BOOL_142 1
#define BLACKDESK_CPPLIB_BOOL_143 1
#define BLACKDESK_CPPLIB_BOOL_144 1
#define BLACKDESK_CPPLIB_BOOL_145 1
#define BLACKDESK_CPPLIB_BOOL_146 1
#define BLACKDESK_CPPLIB_BOOL_147 1
#define BLACKDESK_CPPLIB_BOOL_148 1
#define BLACKDESK_CPPLIB_BOOL_149 1
#define BLACKDESK_CPPLIB_BOOL_150 1
#define BLACKDESK_CPPLIB_BOOL_151 1
#define BLACKDESK_CPPLIB_BOOL_152 1
#define BLACKDESK_CPPLIB_BOOL_153 1
#define BLACKDESK_CPPLIB_BOOL_154 1
#define BLACKDESK_CPPLIB_BOOL_155 1
#define BLACKDESK_CPPLIB_BOOL_156 1
#define BLACKDESK_CPPLIB_BOOL_157 1
#define BLACKDESK_CPPLIB_BOOL_158 1
#define BLACKDESK_CPPLIB_BOOL_159 1
#define BLACKDESK_CPPLIB_BOOL_160 1
#define BLACKDESK_CPPLIB_BOOL_161 1
#define BLACKDESK_CPPLIB_BOOL_162 1
#define BLACKDESK_CPPLIB_BOOL_163 1
#define BLACKDESK_CPPLIB_BOOL_164 1
#define BLACKDESK_CPPLIB_BOOL_165 1
#define BLACKDESK_CPPLIB_BOOL_166 1
#define BLACKDESK_CPPLIB_BOOL_167 1
#define BLACKDESK_CPPLIB_BOOL_168 1
#define BLACKDESK_CPPLIB_BOOL_169 1
#define BLACKDESK_CPPLIB_BOOL_170 1
#define BLACKDESK_CPPLIB_BOOL_171 1
#define BLACKDESK_CPPLIB_BOOL_172 1
#define BLACKDESK_CPPLIB_BOOL_173 1
#define BLACKDESK_CPPLIB_BOOL_174 1
#define BLACKDESK_CPPLIB_BOOL_175 1
#define BLACKDESK_CPPLIB_BOOL_176 1
#define BLACKDESK_CPPLIB_BOOL_177 1
#define BLACKDESK_CPPLIB_BOOL_178 1
#define BLACKDESK_CPPLIB_BOOL_179 1
#define BLACKDESK_CPPLIB_BOOL_180 1
#define BLACKDESK_CPPLIB_BOOL_181 1
#define BLACKDESK_CPPLIB_BOOL_182 1
#define BLACKDESK_CPPLIB_BOOL_183 1
#define BLACKDESK_CPPLIB_BOOL_184 1
#define BLACKDESK_CPPLIB_BOOL_185 1
#define BLACKDESK_CPPLIB_BOOL_186 1
#define BLACKDESK_CPPLIB_BOOL_187 1
#define BLACKDESK_CPPLIB_BOOL_188 1
#define BLACKDESK_CPPLIB_BOOL_189 1
#define BLACKDESK_CPPLIB_BOOL_190 1
#define BLACKDESK_CPPLIB_BOOL_191 1
#define BLACKDESK_CPPLIB_BOOL_192 1
#define BLACKDESK_CPPLIB_BOOL_193 1
#define BLACKDESK_CPPLIB_BOOL_194 1
#define BLACKDESK_CPPLIB_BOOL_195 1
#define BLACKDESK_CPPLIB_BOOL_196 1
#define BLACKDESK_CPPLIB_BOOL_197 1
#define BLACKDESK_CPPLIB_BOOL_198 1
#define BLACKDESK_CPPLIB_BOOL_199 1
#define BLACKDESK_CPPLIB_BOOL_200 1
#define BLACKDESK_CPPLIB_BOOL_201 1
#define BLACKDESK_CPPLIB_BOOL_202 1
#define BLACKDESK_CPPLIB_BOOL_203 1
#define BLACKDESK_CPPLIB_BOOL_204 1
#define BLACKDESK_CPPLIB_BOOL_205 1
#define BLACKDESK_CPPLIB_BOOL_206 1
#define BLACKDESK_CPPLIB_BOOL_207 1
#define BLACKDESK_CPPLIB_BOOL_208 1
#define BLACKDESK_CPPLIB_BOOL_209 1
#define BLACKDESK_CPPLIB_BOOL_210 1
#define BLACKDESK_CPPLIB_BOOL_211 1
#define BLACKDESK_CPPLIB_BOOL_212 1
#define BLACKDESK_CPPLIB_BOOL_213 1
#define BLACKDESK_CPPLIB_BOOL_214 1
#define BLACKDESK_CPPLIB_BOOL_215 1
#define BLACKDESK_CPPLIB_BOOL_216 1
#define BLACKDESK_CPPLIB_BOOL_217 1
#define BLACKDESK_CPPLIB_BOOL_218 1
#define BLACKDESK_CPPLIB_BOOL_219 1
#define BLACKDESK_CPPLIB_BOOL_220 1
#define BLACKDESK_CPPLIB_BOOL_221 1
#define BLACKDESK_CPPLIB_BOOL_222 1
#define BLACKDESK_CPPLIB_BOOL_223 1
#define BLACKDESK_CPPLIB_BOOL_224 1
#define BLACKDESK_CPPLIB_BOOL_225 1
#define BLACKDESK_CPPLIB_BOOL_226 1
#define BLACKDESK_CPPLIB_BOOL_227 1
#define BLACKDESK_CPPLIB_BOOL_228 1
#define BLACKDESK_CPPLIB_BOOL_229 1
#define BLACKDESK_CPPLIB_BOOL_230 1
#define BLACKDESK_CPPLIB_BOOL_231 1
#define BLACKDESK_CPPLIB_BOOL_232 1
#define BLACKDESK_CPPLIB_BOOL_233 1
#define BLACKDESK_CPPLIB_BOOL_234 1
#define BLACKDESK_CPPLIB_BOOL_235 1
#define BLACKDESK_CPPLIB_BOOL_236 1
#define BLACKDESK_CPPLIB_BOOL_237 1
#define BLACKDESK_CPPLIB_BOOL_238 1
#define BLACKDESK_CPPLIB_BOOL_239 1
#define BLACKDESK_CPPLIB_BOOL_240 1
#define BLACKDESK_CPPLIB_BOOL_241 1
#define BLACKDESK_CPPLIB_BOOL_242 1
#define BLACKDESK_CPPLIB_BOOL_243 1
#define BLACKDESK_CPPLIB_BOOL_244 1
#define BLACKDESK_CPPLIB_BOOL_245 1
#define BLACKDESK_CPPLIB_BOOL_246 1
#define BLACKDESK_CPPLIB_BOOL_247 1
#define BLACKDESK_CPPLIB_BOOL_248 1
#define BLACKDESK_CPPLIB_BOOL_249 1
#define BLACKDESK_CPPLIB_BOOL_250 1
#define BLACKDESK_CPPLIB_BOOL_251 1
#define BLACKDESK_CPPLIB_BOOL_252 1
#define BLACKDESK_CPPLIB_BOOL_253 1
#define BLACKDESK_CPPLIB_BOOL_254 1
#define BLACKDESK_CPPLIB_BOOL_255 1

#define BLACKDESK_CPPLIB_NOT(arg0)                     \
        BLACKDESK_CPPLIB_CONCAT(BLACKDESK_CPPLIB_NOT_, \
                                BLACKDESK_CPPLIB_BOOL(arg0))
#define BLACKDESK_CPPLIB_NOT_0 1
#define BLACKDESK_CPPLIB_NOT_1 0

#define BLACKDESK_CPPLIB_AND(arg0, arg1)                             \
        BLACKDESK_CPPLIB_CONCAT(                                     \
                BLACKDESK_CPPLIB_AND_,                               \
                BLACKDESK_CPPLIB_CONCAT(BLACKDESK_CPPLIB_BOOL(arg0), \
                                        BLACKDESK_CPPLIB_BOOL(arg1)))
#define BLACKDESK_CPPLIB_AND_00 0
#define BLACKDESK_CPPLIB_AND_01 0
#define BLACKDESK_CPPLIB_AND_10 0
#define BLACKDESK_CPPLIB_AND_11 1

#define BLACKDESK_CPPLIB_OR(arg0, arg1)                              \
        BLACKDESK_CPPLIB_CONCAT(                                     \
                BLACKDESK_CPPLIB_OR_,                                \
                BLACKDESK_CPPLIB_CONCAT(BLACKDESK_CPPLIB_BOOL(arg0), \
                                        BLACKDESK_CPPLIB_BOOL(arg1)))
#define BLACKDESK_CPPLIB_OR_00 0
#define BLACKDESK_CPPLIB_OR_01 1
#define BLACKDESK_CPPLIB_OR_10 1
#define BLACKDESK_CPPLIB_OR_11 1

#define BLACKDESK_CPPLIB_IF(if, then, else)                \
        BLACKDESK_CPPLIB_CONCAT(BLACKDESK_CPPLIB_IF_,      \
                                BLACKDESK_CPPLIB_BOOL(if)) \
        (then, else)
#define BLACKDESK_CPPLIB_IF_1(then, else) then
#define BLACKDESK_CPPLIB_IF_0(then, else) else

#define BLACKDESK_CPPLIB_INC(arg0) \
        BLACKDESK_CPPLIB_CONCAT(BLACKDESK_CPPLIB_INC_, arg0)
#define BLACKDESK_CPPLIB_INC_0 1
#define BLACKDESK_CPPLIB_INC_1 2
#define BLACKDESK_CPPLIB_INC_2 3
#define BLACKDESK_CPPLIB_INC_3 4
#define BLACKDESK_CPPLIB_INC_4 5
#define BLACKDESK_CPPLIB_INC_5 6
#define BLACKDESK_CPPLIB_INC_6 7
#define BLACKDESK_CPPLIB_INC_7 8
#define BLACKDESK_CPPLIB_INC_8 9
#define BLACKDESK_CPPLIB_INC_9 10
#define BLACKDESK_CPPLIB_INC_10 11
#define BLACKDESK_CPPLIB_INC_11 12
#define BLACKDESK_CPPLIB_INC_12 13
#define BLACKDESK_CPPLIB_INC_13 14
#define BLACKDESK_CPPLIB_INC_14 15
#define BLACKDESK_CPPLIB_INC_15 16
#define BLACKDESK_CPPLIB_INC_16 17
#define BLACKDESK_CPPLIB_INC_17 18
#define BLACKDESK_CPPLIB_INC_18 19
#define BLACKDESK_CPPLIB_INC_19 20
#define BLACKDESK_CPPLIB_INC_20 21
#define BLACKDESK_CPPLIB_INC_21 22
#define BLACKDESK_CPPLIB_INC_22 23
#define BLACKDESK_CPPLIB_INC_23 24
#define BLACKDESK_CPPLIB_INC_24 25
#define BLACKDESK_CPPLIB_INC_25 26
#define BLACKDESK_CPPLIB_INC_26 27
#define BLACKDESK_CPPLIB_INC_27 28
#define BLACKDESK_CPPLIB_INC_28 29
#define BLACKDESK_CPPLIB_INC_29 30
#define BLACKDESK_CPPLIB_INC_30 31
#define BLACKDESK_CPPLIB_INC_31 32
#define BLACKDESK_CPPLIB_INC_32 33
#define BLACKDESK_CPPLIB_INC_33 34
#define BLACKDESK_CPPLIB_INC_34 35
#define BLACKDESK_CPPLIB_INC_35 36
#define BLACKDESK_CPPLIB_INC_36 37
#define BLACKDESK_CPPLIB_INC_37 38
#define BLACKDESK_CPPLIB_INC_38 39
#define BLACKDESK_CPPLIB_INC_39 40
#define BLACKDESK_CPPLIB_INC_40 41
#define BLACKDESK_CPPLIB_INC_41 42
#define BLACKDESK_CPPLIB_INC_42 43
#define BLACKDESK_CPPLIB_INC_43 44
#define BLACKDESK_CPPLIB_INC_44 45
#define BLACKDESK_CPPLIB_INC_45 46
#define BLACKDESK_CPPLIB_INC_46 47
#define BLACKDESK_CPPLIB_INC_47 48
#define BLACKDESK_CPPLIB_INC_48 49
#define BLACKDESK_CPPLIB_INC_49 50
#define BLACKDESK_CPPLIB_INC_50 51
#define BLACKDESK_CPPLIB_INC_51 52
#define BLACKDESK_CPPLIB_INC_52 53
#define BLACKDESK_CPPLIB_INC_53 54
#define BLACKDESK_CPPLIB_INC_54 55
#define BLACKDESK_CPPLIB_INC_55 56
#define BLACKDESK_CPPLIB_INC_56 57
#define BLACKDESK_CPPLIB_INC_57 58
#define BLACKDESK_CPPLIB_INC_58 59
#define BLACKDESK_CPPLIB_INC_59 60
#define BLACKDESK_CPPLIB_INC_60 61
#define BLACKDESK_CPPLIB_INC_61 62
#define BLACKDESK_CPPLIB_INC_62 63
#define BLACKDESK_CPPLIB_INC_63 64
#define BLACKDESK_CPPLIB_INC_64 65
#define BLACKDESK_CPPLIB_INC_65 66
#define BLACKDESK_CPPLIB_INC_66 67
#define BLACKDESK_CPPLIB_INC_67 68
#define BLACKDESK_CPPLIB_INC_68 69
#define BLACKDESK_CPPLIB_INC_69 70
#define BLACKDESK_CPPLIB_INC_70 71
#define BLACKDESK_CPPLIB_INC_71 72
#define BLACKDESK_CPPLIB_INC_72 73
#define BLACKDESK_CPPLIB_INC_73 74
#define BLACKDESK_CPPLIB_INC_74 75
#define BLACKDESK_CPPLIB_INC_75 76
#define BLACKDESK_CPPLIB_INC_76 77
#define BLACKDESK_CPPLIB_INC_77 78
#define BLACKDESK_CPPLIB_INC_78 79
#define BLACKDESK_CPPLIB_INC_79 80
#define BLACKDESK_CPPLIB_INC_80 81
#define BLACKDESK_CPPLIB_INC_81 82
#define BLACKDESK_CPPLIB_INC_82 83
#define BLACKDESK_CPPLIB_INC_83 84
#define BLACKDESK_CPPLIB_INC_84 85
#define BLACKDESK_CPPLIB_INC_85 86
#define BLACKDESK_CPPLIB_INC_86 87
#define BLACKDESK_CPPLIB_INC_87 88
#define BLACKDESK_CPPLIB_INC_88 89
#define BLACKDESK_CPPLIB_INC_89 90
#define BLACKDESK_CPPLIB_INC_90 91
#define BLACKDESK_CPPLIB_INC_91 92
#define BLACKDESK_CPPLIB_INC_92 93
#define BLACKDESK_CPPLIB_INC_93 94
#define BLACKDESK_CPPLIB_INC_94 95
#define BLACKDESK_CPPLIB_INC_95 96
#define BLACKDESK_CPPLIB_INC_96 97
#define BLACKDESK_CPPLIB_INC_97 98
#define BLACKDESK_CPPLIB_INC_98 99
#define BLACKDESK_CPPLIB_INC_99 100
#define BLACKDESK_CPPLIB_INC_100 101
#define BLACKDESK_CPPLIB_INC_101 102
#define BLACKDESK_CPPLIB_INC_102 103
#define BLACKDESK_CPPLIB_INC_103 104
#define BLACKDESK_CPPLIB_INC_104 105
#define BLACKDESK_CPPLIB_INC_105 106
#define BLACKDESK_CPPLIB_INC_106 107
#define BLACKDESK_CPPLIB_INC_107 108
#define BLACKDESK_CPPLIB_INC_108 109
#define BLACKDESK_CPPLIB_INC_109 110
#define BLACKDESK_CPPLIB_INC_110 111
#define BLACKDESK_CPPLIB_INC_111 112
#define BLACKDESK_CPPLIB_INC_112 113
#define BLACKDESK_CPPLIB_INC_113 114
#define BLACKDESK_CPPLIB_INC_114 115
#define BLACKDESK_CPPLIB_INC_115 116
#define BLACKDESK_CPPLIB_INC_116 117
#define BLACKDESK_CPPLIB_INC_117 118
#define BLACKDESK_CPPLIB_INC_118 119
#define BLACKDESK_CPPLIB_INC_119 120
#define BLACKDESK_CPPLIB_INC_120 121
#define BLACKDESK_CPPLIB_INC_121 122
#define BLACKDESK_CPPLIB_INC_122 123
#define BLACKDESK_CPPLIB_INC_123 124
#define BLACKDESK_CPPLIB_INC_124 125
#define BLACKDESK_CPPLIB_INC_125 126
#define BLACKDESK_CPPLIB_INC_126 127
#define BLACKDESK_CPPLIB_INC_127 128
#define BLACKDESK_CPPLIB_INC_128 129
#define BLACKDESK_CPPLIB_INC_129 130
#define BLACKDESK_CPPLIB_INC_130 131
#define BLACKDESK_CPPLIB_INC_131 132
#define BLACKDESK_CPPLIB_INC_132 133
#define BLACKDESK_CPPLIB_INC_133 134
#define BLACKDESK_CPPLIB_INC_134 135
#define BLACKDESK_CPPLIB_INC_135 136
#define BLACKDESK_CPPLIB_INC_136 137
#define BLACKDESK_CPPLIB_INC_137 138
#define BLACKDESK_CPPLIB_INC_138 139
#define BLACKDESK_CPPLIB_INC_139 140
#define BLACKDESK_CPPLIB_INC_140 141
#define BLACKDESK_CPPLIB_INC_141 142
#define BLACKDESK_CPPLIB_INC_142 143
#define BLACKDESK_CPPLIB_INC_143 144
#define BLACKDESK_CPPLIB_INC_144 145
#define BLACKDESK_CPPLIB_INC_145 146
#define BLACKDESK_CPPLIB_INC_146 147
#define BLACKDESK_CPPLIB_INC_147 148
#define BLACKDESK_CPPLIB_INC_148 149
#define BLACKDESK_CPPLIB_INC_149 150
#define BLACKDESK_CPPLIB_INC_150 151
#define BLACKDESK_CPPLIB_INC_151 152
#define BLACKDESK_CPPLIB_INC_152 153
#define BLACKDESK_CPPLIB_INC_153 154
#define BLACKDESK_CPPLIB_INC_154 155
#define BLACKDESK_CPPLIB_INC_155 156
#define BLACKDESK_CPPLIB_INC_156 157
#define BLACKDESK_CPPLIB_INC_157 158
#define BLACKDESK_CPPLIB_INC_158 159
#define BLACKDESK_CPPLIB_INC_159 160
#define BLACKDESK_CPPLIB_INC_160 161
#define BLACKDESK_CPPLIB_INC_161 162
#define BLACKDESK_CPPLIB_INC_162 163
#define BLACKDESK_CPPLIB_INC_163 164
#define BLACKDESK_CPPLIB_INC_164 165
#define BLACKDESK_CPPLIB_INC_165 166
#define BLACKDESK_CPPLIB_INC_166 167
#define BLACKDESK_CPPLIB_INC_167 168
#define BLACKDESK_CPPLIB_INC_168 169
#define BLACKDESK_CPPLIB_INC_169 170
#define BLACKDESK_CPPLIB_INC_170 171
#define BLACKDESK_CPPLIB_INC_171 172
#define BLACKDESK_CPPLIB_INC_172 173
#define BLACKDESK_CPPLIB_INC_173 174
#define BLACKDESK_CPPLIB_INC_174 175
#define BLACKDESK_CPPLIB_INC_175 176
#define BLACKDESK_CPPLIB_INC_176 177
#define BLACKDESK_CPPLIB_INC_177 178
#define BLACKDESK_CPPLIB_INC_178 179
#define BLACKDESK_CPPLIB_INC_179 180
#define BLACKDESK_CPPLIB_INC_180 181
#define BLACKDESK_CPPLIB_INC_181 182
#define BLACKDESK_CPPLIB_INC_182 183
#define BLACKDESK_CPPLIB_INC_183 184
#define BLACKDESK_CPPLIB_INC_184 185
#define BLACKDESK_CPPLIB_INC_185 186
#define BLACKDESK_CPPLIB_INC_186 187
#define BLACKDESK_CPPLIB_INC_187 188
#define BLACKDESK_CPPLIB_INC_188 189
#define BLACKDESK_CPPLIB_INC_189 190
#define BLACKDESK_CPPLIB_INC_190 191
#define BLACKDESK_CPPLIB_INC_191 192
#define BLACKDESK_CPPLIB_INC_192 193
#define BLACKDESK_CPPLIB_INC_193 194
#define BLACKDESK_CPPLIB_INC_194 195
#define BLACKDESK_CPPLIB_INC_195 196
#define BLACKDESK_CPPLIB_INC_196 197
#define BLACKDESK_CPPLIB_INC_197 198
#define BLACKDESK_CPPLIB_INC_198 199
#define BLACKDESK_CPPLIB_INC_199 200
#define BLACKDESK_CPPLIB_INC_200 201
#define BLACKDESK_CPPLIB_INC_201 202
#define BLACKDESK_CPPLIB_INC_202 203
#define BLACKDESK_CPPLIB_INC_203 204
#define BLACKDESK_CPPLIB_INC_204 205
#define BLACKDESK_CPPLIB_INC_205 206
#define BLACKDESK_CPPLIB_INC_206 207
#define BLACKDESK_CPPLIB_INC_207 208
#define BLACKDESK_CPPLIB_INC_208 209
#define BLACKDESK_CPPLIB_INC_209 210
#define BLACKDESK_CPPLIB_INC_210 211
#define BLACKDESK_CPPLIB_INC_211 212
#define BLACKDESK_CPPLIB_INC_212 213
#define BLACKDESK_CPPLIB_INC_213 214
#define BLACKDESK_CPPLIB_INC_214 215
#define BLACKDESK_CPPLIB_INC_215 216
#define BLACKDESK_CPPLIB_INC_216 217
#define BLACKDESK_CPPLIB_INC_217 218
#define BLACKDESK_CPPLIB_INC_218 219
#define BLACKDESK_CPPLIB_INC_219 220
#define BLACKDESK_CPPLIB_INC_220 221
#define BLACKDESK_CPPLIB_INC_221 222
#define BLACKDESK_CPPLIB_INC_222 223
#define BLACKDESK_CPPLIB_INC_223 224
#define BLACKDESK_CPPLIB_INC_224 225
#define BLACKDESK_CPPLIB_INC_225 226
#define BLACKDESK_CPPLIB_INC_226 227
#define BLACKDESK_CPPLIB_INC_227 228
#define BLACKDESK_CPPLIB_INC_228 229
#define BLACKDESK_CPPLIB_INC_229 230
#define BLACKDESK_CPPLIB_INC_230 231
#define BLACKDESK_CPPLIB_INC_231 232
#define BLACKDESK_CPPLIB_INC_232 233
#define BLACKDESK_CPPLIB_INC_233 234
#define BLACKDESK_CPPLIB_INC_234 235
#define BLACKDESK_CPPLIB_INC_235 236
#define BLACKDESK_CPPLIB_INC_236 237
#define BLACKDESK_CPPLIB_INC_237 238
#define BLACKDESK_CPPLIB_INC_238 239
#define BLACKDESK_CPPLIB_INC_239 240
#define BLACKDESK_CPPLIB_INC_240 241
#define BLACKDESK_CPPLIB_INC_241 242
#define BLACKDESK_CPPLIB_INC_242 243
#define BLACKDESK_CPPLIB_INC_243 244
#define BLACKDESK_CPPLIB_INC_244 245
#define BLACKDESK_CPPLIB_INC_245 246
#define BLACKDESK_CPPLIB_INC_246 247
#define BLACKDESK_CPPLIB_INC_247 248
#define BLACKDESK_CPPLIB_INC_248 249
#define BLACKDESK_CPPLIB_INC_249 250
#define BLACKDESK_CPPLIB_INC_250 251
#define BLACKDESK_CPPLIB_INC_251 252
#define BLACKDESK_CPPLIB_INC_252 253
#define BLACKDESK_CPPLIB_INC_253 254
#define BLACKDESK_CPPLIB_INC_254 255
#define BLACKDESK_CPPLIB_INC_255 256
#define BLACKDESK_CPPLIB_INC_256 256

#define BLACKDESK_CPPLIB_DEC(arg0) \
        BLACKDESK_CPPLIB_CONCAT(BLACKDESK_CPPLIB_DEC_, arg0)
#define BLACKDESK_CPPLIB_DEC_0 0
#define BLACKDESK_CPPLIB_DEC_1 0
#define BLACKDESK_CPPLIB_DEC_2 1
#define BLACKDESK_CPPLIB_DEC_3 2
#define BLACKDESK_CPPLIB_DEC_4 3
#define BLACKDESK_CPPLIB_DEC_5 4
#define BLACKDESK_CPPLIB_DEC_6 5
#define BLACKDESK_CPPLIB_DEC_7 6
#define BLACKDESK_CPPLIB_DEC_8 7
#define BLACKDESK_CPPLIB_DEC_9 8
#define BLACKDESK_CPPLIB_DEC_10 9
#define BLACKDESK_CPPLIB_DEC_11 10
#define BLACKDESK_CPPLIB_DEC_12 11
#define BLACKDESK_CPPLIB_DEC_13 12
#define BLACKDESK_CPPLIB_DEC_14 13
#define BLACKDESK_CPPLIB_DEC_15 14
#define BLACKDESK_CPPLIB_DEC_16 15
#define BLACKDESK_CPPLIB_DEC_17 16
#define BLACKDESK_CPPLIB_DEC_18 17
#define BLACKDESK_CPPLIB_DEC_19 18
#define BLACKDESK_CPPLIB_DEC_20 19
#define BLACKDESK_CPPLIB_DEC_21 20
#define BLACKDESK_CPPLIB_DEC_22 21
#define BLACKDESK_CPPLIB_DEC_23 22
#define BLACKDESK_CPPLIB_DEC_24 23
#define BLACKDESK_CPPLIB_DEC_25 24
#define BLACKDESK_CPPLIB_DEC_26 25
#define BLACKDESK_CPPLIB_DEC_27 26
#define BLACKDESK_CPPLIB_DEC_28 27
#define BLACKDESK_CPPLIB_DEC_29 28
#define BLACKDESK_CPPLIB_DEC_30 29
#define BLACKDESK_CPPLIB_DEC_31 30
#define BLACKDESK_CPPLIB_DEC_32 31
#define BLACKDESK_CPPLIB_DEC_33 32
#define BLACKDESK_CPPLIB_DEC_34 33
#define BLACKDESK_CPPLIB_DEC_35 34
#define BLACKDESK_CPPLIB_DEC_36 35
#define BLACKDESK_CPPLIB_DEC_37 36
#define BLACKDESK_CPPLIB_DEC_38 37
#define BLACKDESK_CPPLIB_DEC_39 38
#define BLACKDESK_CPPLIB_DEC_40 39
#define BLACKDESK_CPPLIB_DEC_41 40
#define BLACKDESK_CPPLIB_DEC_42 41
#define BLACKDESK_CPPLIB_DEC_43 42
#define BLACKDESK_CPPLIB_DEC_44 43
#define BLACKDESK_CPPLIB_DEC_45 44
#define BLACKDESK_CPPLIB_DEC_46 45
#define BLACKDESK_CPPLIB_DEC_47 46
#define BLACKDESK_CPPLIB_DEC_48 47
#define BLACKDESK_CPPLIB_DEC_49 48
#define BLACKDESK_CPPLIB_DEC_50 49
#define BLACKDESK_CPPLIB_DEC_51 50
#define BLACKDESK_CPPLIB_DEC_52 51
#define BLACKDESK_CPPLIB_DEC_53 52
#define BLACKDESK_CPPLIB_DEC_54 53
#define BLACKDESK_CPPLIB_DEC_55 54
#define BLACKDESK_CPPLIB_DEC_56 55
#define BLACKDESK_CPPLIB_DEC_57 56
#define BLACKDESK_CPPLIB_DEC_58 57
#define BLACKDESK_CPPLIB_DEC_59 58
#define BLACKDESK_CPPLIB_DEC_60 59
#define BLACKDESK_CPPLIB_DEC_61 60
#define BLACKDESK_CPPLIB_DEC_62 61
#define BLACKDESK_CPPLIB_DEC_63 62
#define BLACKDESK_CPPLIB_DEC_64 63
#define BLACKDESK_CPPLIB_DEC_65 64
#define BLACKDESK_CPPLIB_DEC_66 65
#define BLACKDESK_CPPLIB_DEC_67 66
#define BLACKDESK_CPPLIB_DEC_68 67
#define BLACKDESK_CPPLIB_DEC_69 68
#define BLACKDESK_CPPLIB_DEC_70 69
#define BLACKDESK_CPPLIB_DEC_71 70
#define BLACKDESK_CPPLIB_DEC_72 71
#define BLACKDESK_CPPLIB_DEC_73 72
#define BLACKDESK_CPPLIB_DEC_74 73
#define BLACKDESK_CPPLIB_DEC_75 74
#define BLACKDESK_CPPLIB_DEC_76 75
#define BLACKDESK_CPPLIB_DEC_77 76
#define BLACKDESK_CPPLIB_DEC_78 77
#define BLACKDESK_CPPLIB_DEC_79 78
#define BLACKDESK_CPPLIB_DEC_80 79
#define BLACKDESK_CPPLIB_DEC_81 80
#define BLACKDESK_CPPLIB_DEC_82 81
#define BLACKDESK_CPPLIB_DEC_83 82
#define BLACKDESK_CPPLIB_DEC_84 83
#define BLACKDESK_CPPLIB_DEC_85 84
#define BLACKDESK_CPPLIB_DEC_86 85
#define BLACKDESK_CPPLIB_DEC_87 86
#define BLACKDESK_CPPLIB_DEC_88 87
#define BLACKDESK_CPPLIB_DEC_89 88
#define BLACKDESK_CPPLIB_DEC_90 89
#define BLACKDESK_CPPLIB_DEC_91 90
#define BLACKDESK_CPPLIB_DEC_92 91
#define BLACKDESK_CPPLIB_DEC_93 92
#define BLACKDESK_CPPLIB_DEC_94 93
#define BLACKDESK_CPPLIB_DEC_95 94
#define BLACKDESK_CPPLIB_DEC_96 95
#define BLACKDESK_CPPLIB_DEC_97 96
#define BLACKDESK_CPPLIB_DEC_98 97
#define BLACKDESK_CPPLIB_DEC_99 98
#define BLACKDESK_CPPLIB_DEC_100 99
#define BLACKDESK_CPPLIB_DEC_101 100
#define BLACKDESK_CPPLIB_DEC_102 101
#define BLACKDESK_CPPLIB_DEC_103 102
#define BLACKDESK_CPPLIB_DEC_104 103
#define BLACKDESK_CPPLIB_DEC_105 104
#define BLACKDESK_CPPLIB_DEC_106 105
#define BLACKDESK_CPPLIB_DEC_107 106
#define BLACKDESK_CPPLIB_DEC_108 107
#define BLACKDESK_CPPLIB_DEC_109 108
#define BLACKDESK_CPPLIB_DEC_110 109
#define BLACKDESK_CPPLIB_DEC_111 110
#define BLACKDESK_CPPLIB_DEC_112 111
#define BLACKDESK_CPPLIB_DEC_113 112
#define BLACKDESK_CPPLIB_DEC_114 113
#define BLACKDESK_CPPLIB_DEC_115 114
#define BLACKDESK_CPPLIB_DEC_116 115
#define BLACKDESK_CPPLIB_DEC_117 116
#define BLACKDESK_CPPLIB_DEC_118 117
#define BLACKDESK_CPPLIB_DEC_119 118
#define BLACKDESK_CPPLIB_DEC_120 119
#define BLACKDESK_CPPLIB_DEC_121 120
#define BLACKDESK_CPPLIB_DEC_122 121
#define BLACKDESK_CPPLIB_DEC_123 122
#define BLACKDESK_CPPLIB_DEC_124 123
#define BLACKDESK_CPPLIB_DEC_125 124
#define BLACKDESK_CPPLIB_DEC_126 125
#define BLACKDESK_CPPLIB_DEC_127 126
#define BLACKDESK_CPPLIB_DEC_128 127
#define BLACKDESK_CPPLIB_DEC_129 128
#define BLACKDESK_CPPLIB_DEC_130 129
#define BLACKDESK_CPPLIB_DEC_131 130
#define BLACKDESK_CPPLIB_DEC_132 131
#define BLACKDESK_CPPLIB_DEC_133 132
#define BLACKDESK_CPPLIB_DEC_134 133
#define BLACKDESK_CPPLIB_DEC_135 134
#define BLACKDESK_CPPLIB_DEC_136 135
#define BLACKDESK_CPPLIB_DEC_137 136
#define BLACKDESK_CPPLIB_DEC_138 137
#define BLACKDESK_CPPLIB_DEC_139 138
#define BLACKDESK_CPPLIB_DEC_140 139
#define BLACKDESK_CPPLIB_DEC_141 140
#define BLACKDESK_CPPLIB_DEC_142 141
#define BLACKDESK_CPPLIB_DEC_143 142
#define BLACKDESK_CPPLIB_DEC_144 143
#define BLACKDESK_CPPLIB_DEC_145 144
#define BLACKDESK_CPPLIB_DEC_146 145
#define BLACKDESK_CPPLIB_DEC_147 146
#define BLACKDESK_CPPLIB_DEC_148 147
#define BLACKDESK_CPPLIB_DEC_149 148
#define BLACKDESK_CPPLIB_DEC_150 149
#define BLACKDESK_CPPLIB_DEC_151 150
#define BLACKDESK_CPPLIB_DEC_152 151
#define BLACKDESK_CPPLIB_DEC_153 152
#define BLACKDESK_CPPLIB_DEC_154 153
#define BLACKDESK_CPPLIB_DEC_155 154
#define BLACKDESK_CPPLIB_DEC_156 155
#define BLACKDESK_CPPLIB_DEC_157 156
#define BLACKDESK_CPPLIB_DEC_158 157
#define BLACKDESK_CPPLIB_DEC_159 158
#define BLACKDESK_CPPLIB_DEC_160 159
#define BLACKDESK_CPPLIB_DEC_161 160
#define BLACKDESK_CPPLIB_DEC_162 161
#define BLACKDESK_CPPLIB_DEC_163 162
#define BLACKDESK_CPPLIB_DEC_164 163
#define BLACKDESK_CPPLIB_DEC_165 164
#define BLACKDESK_CPPLIB_DEC_166 165
#define BLACKDESK_CPPLIB_DEC_167 166
#define BLACKDESK_CPPLIB_DEC_168 167
#define BLACKDESK_CPPLIB_DEC_169 168
#define BLACKDESK_CPPLIB_DEC_170 169
#define BLACKDESK_CPPLIB_DEC_171 170
#define BLACKDESK_CPPLIB_DEC_172 171
#define BLACKDESK_CPPLIB_DEC_173 172
#define BLACKDESK_CPPLIB_DEC_174 173
#define BLACKDESK_CPPLIB_DEC_175 174
#define BLACKDESK_CPPLIB_DEC_176 175
#define BLACKDESK_CPPLIB_DEC_177 176
#define BLACKDESK_CPPLIB_DEC_178 177
#define BLACKDESK_CPPLIB_DEC_179 178
#define BLACKDESK_CPPLIB_DEC_180 179
#define BLACKDESK_CPPLIB_DEC_181 180
#define BLACKDESK_CPPLIB_DEC_182 181
#define BLACKDESK_CPPLIB_DEC_183 182
#define BLACKDESK_CPPLIB_DEC_184 183
#define BLACKDESK_CPPLIB_DEC_185 184
#define BLACKDESK_CPPLIB_DEC_186 185
#define BLACKDESK_CPPLIB_DEC_187 186
#define BLACKDESK_CPPLIB_DEC_188 187
#define BLACKDESK_CPPLIB_DEC_189 188
#define BLACKDESK_CPPLIB_DEC_190 189
#define BLACKDESK_CPPLIB_DEC_191 190
#define BLACKDESK_CPPLIB_DEC_192 191
#define BLACKDESK_CPPLIB_DEC_193 192
#define BLACKDESK_CPPLIB_DEC_194 193
#define BLACKDESK_CPPLIB_DEC_195 194
#define BLACKDESK_CPPLIB_DEC_196 195
#define BLACKDESK_CPPLIB_DEC_197 196
#define BLACKDESK_CPPLIB_DEC_198 197
#define BLACKDESK_CPPLIB_DEC_199 198
#define BLACKDESK_CPPLIB_DEC_200 199
#define BLACKDESK_CPPLIB_DEC_201 200
#define BLACKDESK_CPPLIB_DEC_202 201
#define BLACKDESK_CPPLIB_DEC_203 202
#define BLACKDESK_CPPLIB_DEC_204 203
#define BLACKDESK_CPPLIB_DEC_205 204
#define BLACKDESK_CPPLIB_DEC_206 205
#define BLACKDESK_CPPLIB_DEC_207 206
#define BLACKDESK_CPPLIB_DEC_208 207
#define BLACKDESK_CPPLIB_DEC_209 208
#define BLACKDESK_CPPLIB_DEC_210 209
#define BLACKDESK_CPPLIB_DEC_211 210
#define BLACKDESK_CPPLIB_DEC_212 211
#define BLACKDESK_CPPLIB_DEC_213 212
#define BLACKDESK_CPPLIB_DEC_214 213
#define BLACKDESK_CPPLIB_DEC_215 214
#define BLACKDESK_CPPLIB_DEC_216 215
#define BLACKDESK_CPPLIB_DEC_217 216
#define BLACKDESK_CPPLIB_DEC_218 217
#define BLACKDESK_CPPLIB_DEC_219 218
#define BLACKDESK_CPPLIB_DEC_220 219
#define BLACKDESK_CPPLIB_DEC_221 220
#define BLACKDESK_CPPLIB_DEC_222 221
#define BLACKDESK_CPPLIB_DEC_223 222
#define BLACKDESK_CPPLIB_DEC_224 223
#define BLACKDESK_CPPLIB_DEC_225 224
#define BLACKDESK_CPPLIB_DEC_226 225
#define BLACKDESK_CPPLIB_DEC_227 226
#define BLACKDESK_CPPLIB_DEC_228 227
#define BLACKDESK_CPPLIB_DEC_229 228
#define BLACKDESK_CPPLIB_DEC_230 229
#define BLACKDESK_CPPLIB_DEC_231 230
#define BLACKDESK_CPPLIB_DEC_232 231
#define BLACKDESK_CPPLIB_DEC_233 232
#define BLACKDESK_CPPLIB_DEC_234 233
#define BLACKDESK_CPPLIB_DEC_235 234
#define BLACKDESK_CPPLIB_DEC_236 235
#define BLACKDESK_CPPLIB_DEC_237 236
#define BLACKDESK_CPPLIB_DEC_238 237
#define BLACKDESK_CPPLIB_DEC_239 238
#define BLACKDESK_CPPLIB_DEC_240 239
#define BLACKDESK_CPPLIB_DEC_241 240
#define BLACKDESK_CPPLIB_DEC_242 241
#define BLACKDESK_CPPLIB_DEC_243 242
#define BLACKDESK_CPPLIB_DEC_244 243
#define BLACKDESK_CPPLIB_DEC_245 244
#define BLACKDESK_CPPLIB_DEC_246 245
#define BLACKDESK_CPPLIB_DEC_247 246
#define BLACKDESK_CPPLIB_DEC_248 247
#define BLACKDESK_CPPLIB_DEC_249 248
#define BLACKDESK_CPPLIB_DEC_250 249
#define BLACKDESK_CPPLIB_DEC_251 250
#define BLACKDESK_CPPLIB_DEC_252 251
#define BLACKDESK_CPPLIB_DEC_253 252
#define BLACKDESK_CPPLIB_DEC_254 253
#define BLACKDESK_CPPLIB_DEC_255 254
#define BLACKDESK_CPPLIB_DEC_256 255

#define BLACKDESK_CPPLIB_IS_BEGIN_PARENS(...)                  \
        BLACKDESK_CPPLIB_IS_BEGIN_PARENS_PROCESS(              \
                BLACKDESK_CPPLIB_IS_BEGIN_PARENS_CONCAT(       \
                        BLACKDESK_CPPLIB_IS_BEGIN_PARENS_PRE_, \
                        BLACKDESK_CPPLIB_IS_BEGIN_PARENS_EAT __VA_ARGS__))

#define BLACKDESK_CPPLIB_IS_BEGIN_PARENS_PROCESS(...) \
        BLACKDESK_CPPLIB_IS_BEGIN_PARENS_PROCESS_0(__VA_ARGS__)
#define BLACKDESK_CPPLIB_IS_BEGIN_PARENS_PROCESS_0(arg0, ...) arg0

#define BLACKDESK_CPPLIB_IS_BEGIN_PARENS_CONCAT(arg0, ...) \
        BLACKDESK_CPPLIB_IS_BEGIN_PARENS_CONCAT_IMPL(arg0, __VA_ARGS__)
#define BLACKDESK_CPPLIB_IS_BEGIN_PARENS_CONCAT_IMPL(arg0, ...) \
        arg0##__VA_ARGS__

#define BLACKDESK_CPPLIB_IS_BEGIN_PARENS_PRE_1 1,
#define BLACKDESK_CPPLIB_IS_BEGIN_PARENS_PRE_BLACKDESK_CPPLIB_IS_BEGIN_PARENS_EAT \
        0,
#define BLACKDESK_CPPLIB_IS_BEGIN_PARENS_EAT(...) 1

#define BLACKDESK_CPPLIB_IS_EMPTY_PROCESS(...) \
        BLACKDESK_CPPLIB_IS_BEGIN_PARENS(      \
                BLACKDESK_CPPLIB_IS_EMPTY_PROCESS_EAT __VA_ARGS__())
#define BLACKDESK_CPPLIB_IS_EMPTY_PROCESS_EAT(...) ()

#define BLACKDESK_CPPLIB_IS_EMPTY(...)                         \
        BLACKDESK_CPPLIB_IS_EMPTY_IF(                          \
                BLACKDESK_CPPLIB_IS_BEGIN_PARENS(__VA_ARGS__)) \
        (BLACKDESK_CPPLIB_IS_EMPTY_ZERO,                       \
         BLACKDESK_CPPLIB_IS_EMPTY_PROCESS)(__VA_ARGS__)

#define BLACKDESK_CPPLIB_IS_EMPTY_IF(if) \
        BLACKDESK_CPPLIB_CONCAT(BLACKDESK_CPPLIB_IS_EMPTY_IF_, if)
#define BLACKDESK_CPPLIB_IS_EMPTY_IF_1(then, else) then
#define BLACKDESK_CPPLIB_IS_EMPTY_IF_0(then, else) else

#define BLACKDESK_CPPLIB_IS_EMPTY_ZERO(...) 0

#define BLACKDESK_CPPLIB_ARGS_ELEM(I, ...)                      \
        BLACKDESK_CPPLIB_CONCAT(BLACKDESK_CPPLIB_ARGS_ELEM_, I) \
        (__VA_ARGS__)
#define BLACKDESK_CPPLIB_ARGS_ELEM_0(a0, ...) a0
#define BLACKDESK_CPPLIB_ARGS_ELEM_1(a0, a1, ...) a1
#define BLACKDESK_CPPLIB_ARGS_ELEM_2(a0, a1, a2, ...) a2
#define BLACKDESK_CPPLIB_ARGS_ELEM_3(a0, a1, a2, a3, ...) a3
#define BLACKDESK_CPPLIB_ARGS_ELEM_4(a0, a1, a2, a3, a4, ...) a4
#define BLACKDESK_CPPLIB_ARGS_ELEM_5(a0, a1, a2, a3, a4, a5, ...) a5
#define BLACKDESK_CPPLIB_ARGS_ELEM_6(a0, a1, a2, a3, a4, a5, a6...) a6
#define BLACKDESK_CPPLIB_ARGS_ELEM_7(a0, a1, a2, a3, a4, a5, a6, a7, ...) a7
#define BLACKDESK_CPPLIB_ARGS_ELEM_8(a0, a1, a2, a3, a4, a5, a6, a7, a8, ...) a8

#define BLACKDESK_CPPLIB_ARGS_ELEM_OR_EMPTY(I, ...)                           \
        BLACKDESK_CPPLIB_REMOVE_PARENS(BLACKDESK_CPPLIB_IF(                   \
                BLACKDESK_CPPLIB_CONCAT(                                      \
                        BLACKDESK_CPPLIB_ARGS_FOUND_,                         \
                        BLACKDESK_CPPLIB_DEC(                                 \
                                BLACKDESK_CPPLIB_ARGS_SIZE(__VA_ARGS__)))(I), \
                (BLACKDESK_CPPLIB_ARGS_ELEM(I, __VA_ARGS__, -1, -1, -1, -1,   \
                                            -1, -1, -1, -1)),                 \
                ()))

#define BLACKDESK_CPPLIB_ARGS_FOUND_0(I) \
        BLACKDESK_CPPLIB_ARGS_ELEM(I, 1, 0, 0, 0, 0, 0, 0, 0, 0)
#define BLACKDESK_CPPLIB_ARGS_FOUND_1(I) \
        BLACKDESK_CPPLIB_ARGS_ELEM(I, 1, 1, 0, 0, 0, 0, 0, 0, 0)
#define BLACKDESK_CPPLIB_ARGS_FOUND_2(I) \
        BLACKDESK_CPPLIB_ARGS_ELEM(I, 1, 1, 1, 0, 0, 0, 0, 0, 0)
#define BLACKDESK_CPPLIB_ARGS_FOUND_3(I) \
        BLACKDESK_CPPLIB_ARGS_ELEM(I, 1, 1, 1, 1, 0, 0, 0, 0, 0)
#define BLACKDESK_CPPLIB_ARGS_FOUND_4(I) \
        BLACKDESK_CPPLIB_ARGS_ELEM(I, 1, 1, 1, 1, 1, 0, 0, 0, 0)
#define BLACKDESK_CPPLIB_ARGS_FOUND_5(I) \
        BLACKDESK_CPPLIB_ARGS_ELEM(I, 1, 1, 1, 1, 1, 1, 0, 0, 0)
#define BLACKDESK_CPPLIB_ARGS_FOUND_6(I) \
        BLACKDESK_CPPLIB_ARGS_ELEM(I, 1, 1, 1, 1, 1, 1, 1, 0, 0)
#define BLACKDESK_CPPLIB_ARGS_FOUND_7(I) \
        BLACKDESK_CPPLIB_ARGS_ELEM(I, 1, 1, 1, 1, 1, 1, 1, 1, 0)
#define BLACKDESK_CPPLIB_ARGS_FOUND_8(I) \
        BLACKDESK_CPPLIB_ARGS_ELEM(I, 1, 1, 1, 1, 1, 1, 1, 1, 1)

#define BLACKDESK_CPPLIB_REMOVE_PARENS(tuple) \
        BLACKDESK_CPPLIB_REMOVE_PARENS_IMPL tuple
#define BLACKDESK_CPPLIB_REMOVE_PARENS_IMPL(...) __VA_ARGS__

#define BLACKDESK_CPPLIB_ARGS_OPT(data_tuple, empty_tuple, ...)             \
        BLACKDESK_CPPLIB_ARGS_OPT_IMPL(                                     \
                BLACKDESK_CPPLIB_IF(BLACKDESK_CPPLIB_IS_EMPTY(__VA_ARGS__), \
                                    empty_tuple, data_tuple))
#define BLACKDESK_CPPLIB_ARGS_OPT_IMPL(tuple) \
        BLACKDESK_CPPLIB_REMOVE_PARENS(tuple)

#define BLACKDESK_CPPLIB_ARGS_SIZE_IMCOMPLETE(...) \
        BLACKDESK_CPPLIB_ARGS_ELEM(8, __VA_ARGS__, 8, 7, 6, 5, 4, 3, 2, 1, 0)
#define BLACKDESK_CPPLIB_COMMA_IF_ARGS(...) \
        BLACKDESK_CPPLIB_ARGS_OPT((, ), (), __VA_ARGS__)
#define BLACKDESK_CPPLIB_ARGS_SIZE(...)                                       \
        BLACKDESK_CPPLIB_ARGS_ELEM(                                           \
                8, __VA_ARGS__ BLACKDESK_CPPLIB_COMMA_IF_ARGS(__VA_ARGS__) 8, \
                7, 6, 5, 4, 3, 2, 1, 0, 0, 0)

#define BLACKDESK_CPPLIB_ADD_COMMA_FRONT_IF_ARGS(...) \
        BLACKDESK_CPPLIB_ARGS_OPT((, ), (), __VA_ARGS__) __VA_ARGS__

#define BLACKDESK_CPPLIB_FOR_EACH(macro, contex, ...)                    \
        BLACKDESK_CPPLIB_CONCAT(BLACKDESK_CPPLIB_FOR_EACH_,              \
                                BLACKDESK_CPPLIB_ARGS_SIZE(__VA_ARGS__)) \
        (0, macro, contex, __VA_ARGS__)

#define BLACKDESK_CPPLIB_FOR_EACH_0(index, macro, contex, ...)
#define BLACKDESK_CPPLIB_FOR_EACH_1(index, macro, contex, arg, ...) \
        macro(index, contex, arg)
#define BLACKDESK_CPPLIB_FOR_EACH_2(index, macro, contex, arg, ...) \
        macro(index, contex, arg) BLACKDESK_CPPLIB_FOR_EACH_1(      \
                BLACKDESK_CPPLIB_INC(index), macro, contex, __VA_ARGS__)
#define BLACKDESK_CPPLIB_FOR_EACH_3(index, macro, contex, arg, ...) \
        macro(index, contex, arg) BLACKDESK_CPPLIB_FOR_EACH_2(      \
                BLACKDESK_CPPLIB_INC(index), macro, contex, __VA_ARGS__)
#define BLACKDESK_CPPLIB_FOR_EACH_4(index, macro, contex, arg, ...) \
        macro(index, contex, arg) BLACKDESK_CPPLIB_FOR_EACH_3(      \
                BLACKDESK_CPPLIB_INC(index), macro, contex, __VA_ARGS__)
#define BLACKDESK_CPPLIB_FOR_EACH_5(index, macro, contex, arg, ...) \
        macro(index, contex, arg) BLACKDESK_CPPLIB_FOR_EACH_4(      \
                BLACKDESK_CPPLIB_INC(index), macro, contex, __VA_ARGS__)
#define BLACKDESK_CPPLIB_FOR_EACH_6(index, macro, contex, arg, ...) \
        macro(index, contex, arg) BLACKDESK_CPPLIB_FOR_EACH_5(      \
                BLACKDESK_CPPLIB_INC(index), macro, contex, __VA_ARGS__)
#define BLACKDESK_CPPLIB_FOR_EACH_7(index, macro, contex, arg, ...) \
        macro(index, contex, arg) BLACKDESK_CPPLIB_FOR_EACH_6(      \
                BLACKDESK_CPPLIB_INC(index), macro, contex, __VA_ARGS__)
#define BLACKDESK_CPPLIB_FOR_EACH_8(index, macro, contex, arg, ...) \
        macro(index, contex, arg) BLACKDESK_CPPLIB_FOR_EACH_7(      \
                BLACKDESK_CPPLIB_INC(index), macro, contex, __VA_ARGS__)

#define BLACKDESK_CPPLIB_WHILE BLACKDESK_CPPLIB_WHILE_1

#define BLACKDESK_CPPLIB_WHILE_1(pred, op, val)                               \
        BLACKDESK_CPPLIB_WHILE_1_IMPL(BLACKDESK_CPPLIB_BOOL(pred(val)), pred, \
                                      op, val)
#define BLACKDESK_CPPLIB_WHILE_1_IMPL(cond, pred, op, val)  \
        BLACKDESK_CPPLIB_IF(cond, BLACKDESK_CPPLIB_WHILE_2, \
                            val BLACKDESK_CPPLIB_EMPTY_EAT) \
        (pred, op,                                          \
         BLACKDESK_CPPLIB_IF(cond, op, BLACKDESK_CPPLIB_EMPTY_EAT)(val))
#define BLACKDESK_CPPLIB_WHILE_2(pred, op, val)                               \
        BLACKDESK_CPPLIB_WHILE_2_IMPL(BLACKDESK_CPPLIB_BOOL(pred(val)), pred, \
                                      op, val)
#define BLACKDESK_CPPLIB_WHILE_2_IMPL(cond, pred, op, val)  \
        BLACKDESK_CPPLIB_IF(cond, BLACKDESK_CPPLIB_WHILE_3, \
                            val BLACKDESK_CPPLIB_EMPTY_EAT) \
        (pred, op,                                          \
         BLACKDESK_CPPLIB_IF(cond, op, BLACKDESK_CPPLIB_EMPTY_EAT)(val))
#define BLACKDESK_CPPLIB_WHILE_3(pred, op, val)                               \
        BLACKDESK_CPPLIB_WHILE_3_IMPL(BLACKDESK_CPPLIB_BOOL(pred(val)), pred, \
                                      op, val)
#define BLACKDESK_CPPLIB_WHILE_3_IMPL(cond, pred, op, val)  \
        BLACKDESK_CPPLIB_IF(cond, BLACKDESK_CPPLIB_WHILE_4, \
                            val BLACKDESK_CPPLIB_EMPTY_EAT) \
        (pred, op,                                          \
         BLACKDESK_CPPLIB_IF(cond, op, BLACKDESK_CPPLIB_EMPTY_EAT)(val))
#define BLACKDESK_CPPLIB_WHILE_4(pred, op, val)                               \
        BLACKDESK_CPPLIB_WHILE_4_IMPL(BLACKDESK_CPPLIB_BOOL(pred(val)), pred, \
                                      op, val)
#define BLACKDESK_CPPLIB_WHILE_4_IMPL(cond, pred, op, val)  \
        BLACKDESK_CPPLIB_IF(cond, BLACKDESK_CPPLIB_WHILE_5, \
                            val BLACKDESK_CPPLIB_EMPTY_EAT) \
        (pred, op,                                          \
         BLACKDESK_CPPLIB_IF(cond, op, BLACKDESK_CPPLIB_EMPTY_EAT)(val))
#define BLACKDESK_CPPLIB_WHILE_5(pred, op, val)                               \
        BLACKDESK_CPPLIB_WHILE_5_IMPL(BLACKDESK_CPPLIB_BOOL(pred(val)), pred, \
                                      op, val)
#define BLACKDESK_CPPLIB_WHILE_5_IMPL(cond, pred, op, val)  \
        BLACKDESK_CPPLIB_IF(cond, BLACKDESK_CPPLIB_WHILE_6, \
                            val BLACKDESK_CPPLIB_EMPTY_EAT) \
        (pred, op,                                          \
         BLACKDESK_CPPLIB_IF(cond, op, BLACKDESK_CPPLIB_EMPTY_EAT)(val))
#define BLACKDESK_CPPLIB_WHILE_6(pred, op, val)                               \
        BLACKDESK_CPPLIB_WHILE_6_IMPL(BLACKDESK_CPPLIB_BOOL(pred(val)), pred, \
                                      op, val)
#define BLACKDESK_CPPLIB_WHILE_6_IMPL(cond, pred, op, val)  \
        BLACKDESK_CPPLIB_IF(cond, BLACKDESK_CPPLIB_WHILE_7, \
                            val BLACKDESK_CPPLIB_EMPTY_EAT) \
        (pred, op,                                          \
         BLACKDESK_CPPLIB_IF(cond, op, BLACKDESK_CPPLIB_EMPTY_EAT)(val))
#define BLACKDESK_CPPLIB_WHILE_7(pred, op, val)                               \
        BLACKDESK_CPPLIB_WHILE_7_IMPL(BLACKDESK_CPPLIB_BOOL(pred(val)), pred, \
                                      op, val)
#define BLACKDESK_CPPLIB_WHILE_7_IMPL(cond, pred, op, val)  \
        BLACKDESK_CPPLIB_IF(cond, BLACKDESK_CPPLIB_WHILE_8, \
                            val BLACKDESK_CPPLIB_EMPTY_EAT) \
        (pred, op,                                          \
         BLACKDESK_CPPLIB_IF(cond, op, BLACKDESK_CPPLIB_EMPTY_EAT)(val))
#define BLACKDESK_CPPLIB_WHILE_8(pred, op, val)                               \
        BLACKDESK_CPPLIB_WHILE_8_IMPL(BLACKDESK_CPPLIB_BOOL(pred(val)), pred, \
                                      op, val)
#define BLACKDESK_CPPLIB_WHILE_8_IMPL(cond, pred, op, val)  \
        BLACKDESK_CPPLIB_IF(cond, BLACKDESK_CPPLIB_WHILE_8, \
                            val BLACKDESK_CPPLIB_EMPTY_EAT) \
        (pred, op,                                          \
         BLACKDESK_CPPLIB_IF(cond, op, BLACKDESK_CPPLIB_EMPTY_EAT)(val))

#define BLACKDESK_CPPLIB_EMPTY_EAT(...)
