name: Build and test cpp library

on:
  push:
    paths:
      - .github/workflows/*
      - cpp/**

jobs:
  build-by-gcc:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Install clang-tidy and ninja
      run: sudo apt-get install -y clang-tidy ninja-build

    - name: Build "Debug" and test using g++
      run: |
        cd cpp &&
        rm build -rf &&
        cmake -B build -DCMAKE_GENERATOR=Ninja -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -fsanitize=undefined" \
              -DCMAKE_CXX_CLANG_TIDY=clang-tidy &&
        cmake --build build &&
        cmake --build build -t test

  build-by-clang:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Install clang and clang-tidy
      run: sudo apt-get install -y clang-tidy ninja-build clang

    - name: Build "Debug" and test using clang++
      run: |
        cd cpp &&
        rm build -rf &&
        cmake -B build -DCMAKE_GENERATOR=Ninja -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -fsanitize=undefined" \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_CXX_CLANG_TIDY=clang-tidy &&
        cmake --build build &&
        cmake --build build -t test
