name: Build and test cpp library

on: [pull_request]

jobs:
  build-by-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          workflows:
            - '.github/workflows/*'
          cpp:
            - 'cpp/**'

    - name: Build "Debug" and test using g++
      if: steps.filter.outputs.cpp == 'true' || steps.filter.outputs.workflows == 'true'
      run: |
        sudo apt-get install -y clang-tidy ninja-build &&
        cd cpp &&
        rm build -rf &&
        cmake -B build -DCMAKE_GENERATOR=Ninja -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -fsanitize=undefined" \
              -DCMAKE_CXX_CLANG_TIDY=clang-tidy &&
        cmake --build build &&
        cmake --build build -t test

  build-by-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          workflows:
            - '.github/workflows/*'
          cpp:
            - 'cpp/**'

    - name: Build "Debug" and test using clang++
      if: steps.filter.outputs.cpp == 'true' || steps.filter.outputs.workflows == 'true'
      run: |
        sudo apt-get install -y clang-tidy ninja-build clang &&
        cd cpp &&
        rm build -rf &&
        cmake -B build -DCMAKE_GENERATOR=Ninja -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -fsanitize=undefined" \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_CXX_CLANG_TIDY=clang-tidy &&
        cmake --build build &&
        cmake --build build -t test
