name: Build and test go package

on: [pull_request]

jobs:
  build-go:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            workflows:
              - '.github/workflows/*'
            go:
              - 'go/**'

      - name: Set up Go
        if: steps.filter.outputs.go == 'true' || steps.filter.outputs.workflows == 'true'
        uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: true
          cache-dependency-path: go/go.sum

      - name: Build & test
        if: steps.filter.outputs.go == 'true' || steps.filter.outputs.workflows == 'true'
        run: |
          cd go
          go build -v ./...
          go test -v ./...
